// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACLQe3CkdP3eVDhUOklDTJE2NHPVEnC5M',
    appId: '1:8441977070:web:47447fd2815bda5711fbff',
    messagingSenderId: '8441977070',
    projectId: 'to-do-app-dead7',
    authDomain: 'to-do-app-dead7.firebaseapp.com',
    storageBucket: 'to-do-app-dead7.firebasestorage.app',
    measurementId: 'G-47C8Q0XM8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtb-3Yg_NcVzfxYIlkXBcyThxtAz8M5y0',
    appId: '1:8441977070:android:de4664795a1d806111fbff',
    messagingSenderId: '8441977070',
    projectId: 'to-do-app-dead7',
    storageBucket: 'to-do-app-dead7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6nkw4zz5-I9iNkdUf6ikbvMOQkEUnVQI',
    appId: '1:8441977070:ios:56084fd7188eb48011fbff',
    messagingSenderId: '8441977070',
    projectId: 'to-do-app-dead7',
    storageBucket: 'to-do-app-dead7.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6nkw4zz5-I9iNkdUf6ikbvMOQkEUnVQI',
    appId: '1:8441977070:ios:56084fd7188eb48011fbff',
    messagingSenderId: '8441977070',
    projectId: 'to-do-app-dead7',
    storageBucket: 'to-do-app-dead7.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACLQe3CkdP3eVDhUOklDTJE2NHPVEnC5M',
    appId: '1:8441977070:web:563f9f6012b220c311fbff',
    messagingSenderId: '8441977070',
    projectId: 'to-do-app-dead7',
    authDomain: 'to-do-app-dead7.firebaseapp.com',
    storageBucket: 'to-do-app-dead7.firebasestorage.app',
    measurementId: 'G-QBTBF89JVV',
  );
}
